onEvent('recipes', (event) => {

    const idRemovals = [
        'immersiveengineering:crafting/storage_copper_to_ingot_copper',
        'immersiveengineering:crafting/nugget_copper_to_ingot_copper',
        'immersiveengineering:crafting/storage_silver_to_ingot_silver',
        'immersiveengineering:crafting/nugget_silver_to_ingot_silver',
        'immersiveengineering:crafting/storage_aluminum_to_ingot_aluminum',
        'immersiveengineering:crafting/nugget_aluminum_to_ingot_aluminum',
        'immersiveengineering:crafting/storage_uranium_to_ingot_uranium',
        'immersiveengineering:crafting/nugget_uranium_to_ingot_uranium',
        'immersiveengineering:crafting/storage_lead_to_ingot_lead',
        'immersiveengineering:crafting/nugget_lead_to_ingot_lead',
        'immersiveengineering:crafting/storage_nickel_to_ingot_nickel',
        'immersiveengineering:crafting/nugget_nickel_to_ingot_nickel',
        'immersiveengineering:crafting/storage_steel_to_ingot_steel',
        'immersiveengineering:crafting/nugget_steel_to_ingot_steel',
        'immersiveengineering:crafting/storage_electrum_to_ingot_electrum',
        'immersiveengineering:crafting/nugget_electrum_to_ingot_electrum',
        'immersiveengineering:crafting/storage_constantan_to_ingot_constantan',
        'immersiveengineering:crafting/nugget_constantan_to_ingot_constantan',

        'create:crafting/materials/copper_ingot_from_compacting',
        'create:crafting/materials/copper_ingot_from_decompacting',
        'create:crafting/materials/zinc_ingot_from_compacting',
        'create:crafting/materials/zinc_ingot_from_decompacting',
        
        'projectred-exploration:copper_from_block',
        'projectred-exploration:silver_from_block',
        'projectred-exploration:tin_from_block',

        //'occultism:crafting/copper_ingot_from_block',
        //'occultism:crafting/copper_ingot_from_nuggets',
        //'occultism:crafting/silver_ingot_from_block',
        //'occultism:crafting/silver_ingot_from_nuggets',

        'thermal:storage/copper_ingot_from_block',
        'thermal:storage/copper_ingot_from_nuggets',
        'thermal:storage/silver_ingot_from_block',
        'thermal:storage/silver_ingot_from_nuggets',
        'thermal:storage/tin_ingot_from_block',
        'thermal:storage/tin_ingot_from_nuggets',
        'thermal:storage/lead_ingot_from_block',
        'thermal:storage/lead_ingot_from_nuggets',
        'thermal:storage/nickel_ingot_from_block',
        'thermal:storage/nickel_ingot_from_nuggets',

        'thermal:machine/press/unpacking/press_copper_unpacking',
        'thermal:machine/press/unpacking/press_silver_unpacking',
        'thermal:machine/press/unpacking/press_tin_unpacking',
        'thermal:machine/press/unpacking/press_lead_unpacking',
        'thermal:machine/press/unpacking/press_nickel_unpacking',

        'mekanism:processing/copper/ingot/from_block',
        'mekanism:processing/copper/ingot/from_nuggets',
        'mekanism:processing/tin/ingot/from_block',
        'mekanism:processing/tin/ingot/from_nuggets',
        'mekanism:processing/uranium/ingot/from_block',
        'mekanism:processing/uranium/ingot/from_nuggets',
        'mekanism:processing/lead/ingot/from_block',
        'mekanism:processing/lead/ingot/from_nuggets',
        'mekanism:processing/osmium/ingot/from_block',
        'mekanism:processing/osmium/ingot/from_nuggets',
        'mekanism:processing/bronze/ingot/from_block',
        'mekanism:processing/bronze/ingot/from_nuggets',

        //'cavesandcliffs:copper_ingot',

        'eidolon:lead_ingot',
        'eidolon:decompress_lead_block',

        'werewolves:iron_ingot_from_iron_block',
        'werewolves:silver_ingot_from_nuggets',

        'platinum:platinum_ingot_from_platinum_block',
        'platinum:platinum_ingot_from_platinum_nuggets',

        'bigreactors:crafting/yellorium_storage_to_component',
        'bigreactors:yellorium_ingot_to_nugget',

        //'boss_tools:steel_ingot',
        //'boss_tools:steel_ingot_from_nugget',

        'tconstruct:common/materials/copper_ingot_from_block',
        'tconstruct:common/materials/copper_ingot_from_nuggets',
        'tconstruct:common/slime/lead',

        'iceandfire:copper_ingot',
        'iceandfire:copper_block_to_ingots',
        'iceandfire:silver_ingot',
        'iceandfire:silver_block_to_ingots',

        'bno:copper_ingot-1',
        'bno:copper_ingot-2',
        'bno:silver_ingot-1',
        'bno:silver_ingot-2',
        'bno:aluminum_ingot-1',
        'bno:aluminum_ingot-2',
        'bno:tin_ingot-1',
        'bno:tin_ingot-2',
        'bno:lead_ingot-1',
        'bno:lead_ingot-2',
        'bno:nickel_ingot-1',
        'bno:nickel_ingot-2',
        'bno:osmium_ingot-1',
        'bno:osmium_ingot-2',
        'bno:uranium_ingot',

        'beo:copper_block',
        'beo:copper_ingot',
        'beo:copper_nugget',
        'beo:silver_block',
        'beo:silver_ingot',
        'beo:silver_nugget',
        'beo:aluminum_block',
        'beo:aluminum_ingot',
        'beo:aluminum_nugget',
        'beo:tin_block',
        'beo:tin_ingot',
        'beo:tin_nugget',
        'beo:lead_block',
        'beo:lead_ingot',
        'beo:lead_nugget',
        'beo:nickel_block',
        'beo:nickel_ingot',
        'beo:nickel_nugget',
        'beo:osmium_block',
        'beo:osmium_ingot',
        'beo:osmium_nugget',
        'beo:uranium_block',
        'beo:uranium_ingot',

        'bigreactors:yellorium_component_to_storage',
        'bigreactors:crafting/yellorium_nugget_to_ingot',
        'bigreactors:misc/book/erguide',
        'bigreactors:reactor/basic/controller_ingots_yellorium',
        'bigreactors:reactor/basic/fuelrod_ingots_yellorium',
        'bigreactors:reactor/reinforced/controller_ingots_yellorium',
        'bigreactors:reactor/reinforced/fuelrod_ingots_yellorium',
        'bigreactors:fluidizer/solid/yellorium',
        'bigreactors:fluidizer/solid/yellorium9',
        'create:empty_evilcraft_dark_tank_of_bigreactors_yellorium',
        'create:empty_mekanism_creative_fluid_tank_of_bigreactors_yellorium',
        'create:empty_bigreactors_yellorium_bucket_of_bigreactors_yellorium',

        //'magistuarmory:steel_ingot',
        //'xreliquary:alkahestry/craftinf/steel_ingot',

        'extendedcrafting:handheld_table',

        'the_afterlight:gloom_chest_recipe',
        'the_afterlight:moon_chest_recipe',
        'the_afterlight:gloom_crafting_table_recipe',
        'the_afterlight:moon_crafting_table_recipe_1',
        'the_afterlight:moonstone_sword_recipe_2',
        'the_afterlight:moonstone_shovel_recipe_2',
        'the_afterlight:moonstone_pickaxe_recipe',
        'the_afterlight:moonstone_axe_recipe_1',
        'the_afterlight:moonstone_hoe_recipe_1',
        'the_afterlight:moon_grindstone_recipe',
        'the_afterlight:gloom_grindstone_recipe',
        'the_afterlight:stone_button_afterlight_recipe',
        'the_afterlight:moon_plank_wooden_sword_recipe_1',
        'the_afterlight:gloom_wood_sword_recipe',
        'the_afterlight:moon_plank_wooden_shovel_recipe_2',
        'the_afterlight:gloom_wood_shovel_recipe',
        'the_afterlight:moon_plank_wooden_pickaxe_recipe',
        'the_afterlight:gloom_wood_pickaxe_recipe',
        'the_afterlight:moon_plank_woodeen_axe_recipe_1',
        'the_afterlight:gloom_wood_axe_recipe',
        'the_afterlight:moon_plank_wooden_hoe_recipe_1',
        'the_afterlight:gloom_wood_hoe_recipe',
        'the_afterlight:loom_moon_recipe',
        'the_afterlight:loom_gloom_recipe',
        'the_afterlight:moon_barrel_recipe',
        'the_afterlight:gloom_barrel_recipe',
        'the_afterlight:composter_moon_recipe',
        'the_afterlight:composter_gloom_recipe',
        'the_afterlight:smoker_moon_recipe',
        'the_afterlight:smoker_gloom_recipe',
        'the_afterlight:carto_moon_recipe',
        'the_afterlight:carto_gloom_recipe',
        'the_afterlight:lectern_moon_recipe',
        'the_afterlight:lectern_gloom_recipe',
        'the_afterlight:beehive_afterlight_recipe_1',
        'the_afterlight:beehive_afterlight_recipe_2',
        'the_afterlight:moon_bowl_recipe_2',
        'the_afterlight:moon_furnace_recipe',

        'appliedenergistics2:misc/vanilla_comparator',
        'appliedenergistics2:facade/allthecompressed/nether_star_block',
        'appliedenergistics2:facade/allthecompressed/nether_star_block_1x',
        'appliedenergistics2:facade/allthecompressed/nether_star_block_2x',
        'appliedenergistics2:facade/allthecompressed/nether_star_block_3x',
        'appliedenergistics2:facade/allthecompressed/nether_star_block_4x',
        'appliedenergistics2:facade/allthecompressed/nether_star_block_5x',
        'appliedenergistics2:facade/allthecompressed/nether_star_block_6x',
        'appliedenergistics2:facade/allthecompressed/nether_star_block_7x',
        'appliedenergistics2:facade/allthecompressed/nether_star_block_8x',
        'appliedenergistics2:facade/allthecompressed/nether_star_block_9x',
        'appliedenergistics2:facade/allthecompressed/atm_star_block',
        'appliedenergistics2:facade/allthecompressed/atm_star_block_1x',
        'appliedenergistics2:facade/allthecompressed/atm_star_block_2x',
        'appliedenergistics2:facade/allthecompressed/atm_star_block_3x',
        'appliedenergistics2:facade/allthecompressed/atm_star_block_4x',
        'appliedenergistics2:facade/allthecompressed/atm_star_block_5x',
        'appliedenergistics2:facade/allthecompressed/atm_star_block_6x',
        'appliedenergistics2:facade/allthecompressed/atm_star_block_7x',
        'appliedenergistics2:facade/allthecompressed/atm_star_block_8x',
        'appliedenergistics2:facade/allthecompressed/atm_star_block_9x',
        'appliedenergistics2:facade/stalwart_dungeons/tungsten_ore',
        'appliedenergistics2:facade/stalwart_dungeons/awful_ghast_altar',
        'appliedenergistics2:facade/stalwart_dungeons/nether_keeper_altar',
        'appliedenergistics2:facade/stalwart_dungeons/shelterer_altar',

        'allthecompressed:block/atc/atm_star/compress/1x',
        'allthecompressed:block/atc/atm_star/decompress/1x',
        'allthecompressed:block/atc/atm_star/compress/2x',
        'allthecompressed:block/atc/atm_star/decompress/2x',
        'allthecompressed:block/atc/atm_star/compress/3x',
        'allthecompressed:block/atc/atm_star/decompress/3x',
        'allthecompressed:block/atc/atm_star/compress/4x',
        'allthecompressed:block/atc/atm_star/decompress/4x',
        'allthecompressed:block/atc/atm_star/compress/5x',
        'allthecompressed:block/atc/atm_star/decompress/5x',
        'allthecompressed:block/atc/atm_star/compress/6x',
        'allthecompressed:block/atc/atm_star/decompress/6x',
        'allthecompressed:block/atc/atm_star/compress/7x',
        'allthecompressed:block/atc/atm_star/decompress/7x',
        'allthecompressed:block/atc/atm_star/compress/8x',
        'allthecompressed:block/atc/atm_star/decompress/8x',
        'allthecompressed:block/atc/atm_star/compress/9x',
        'allthecompressed:block/atc/atm_star/decompress/9x',

        'undergarden:undergarden_scaffolding',
        'undergarden:undergarden_lead',

        'minecolonies:chainmailhelmet',
        'minecolonies:chainmailchestplate',
        'minecolonies:chainmailleggings',
        'minecolonies:chainmailboots',
        'iceandfire:chainmail_helmet',
        'iceandfire:chainmail_chestplate',
        'iceandfire:chainmail_leggings',
        'iceandfire:chainmail_boots',
        'mana-and-artifice:chainmail_helmet',
        'mana-and-artifice:chainmail_chestplate',
        'mana-and-artifice:chainmail_leggings',
        'mana-and-artifice:chainmail_boots',
        'goldenagecombat:enchanted_golden_apple',
        'forbidden_arcanus:enchanted_golden_apple',
        'pamhc2crops:paper_x2_paper_plants',
        'charm:block_of_ender_pearls/ender_pearls_from_ender_pearl_block',
        'charm:block_of_gunpowder/gunpowder_block_with_quark',
        'charm:block_of_gunpowder/gunpowder_from_gunpowder_block_with_quark',
        'extendedcrafting:nether_star_block',
        'extendedcrafting:nether_star_block_uncraft',
        'overloaded:blocks/nether_star_from_block',
        'byg:fire_charge_from_byg_coals',
        'biomesoplenty:rabbit_stew_from_toadstool',
        'druidcraft:lead',
        'blue_skies:furnace_compat'



    ]

    idRemovals.forEach((id) => {
        event.remove({ id: id })
    })

})
