
[client]

	#Control sounds triggered by guns
	[client.sounds]
		#If true, a sound will play when you successfully hit a headshot on a entity with a gun
		playSoundWhenHeadshot = true
		#The sound to play when a headshot occurs
		headshotSound = "tac:item.headshot"
		#If true, a sound will play when you successfully hit a critical on a entity with a gun
		playSoundWhenCritical = true
		#The sound to play when a critical occurs
		criticalSound = "minecraft:entity.player.attack.crit"

	#Configuration for display related options
	[client.display]
		#If true, uses the old animation poses for weapons. This is only for nostalgic reasons and not recommended to switch back.
		oldAnimations = false
		#The custom crosshair to use for weapons. Go to (Options > Controls > Mouse Settings > Crosshair) in game to change this!
		crosshair = "minecraft:default"
		#Show % of your ammo in your gun via a colored durability bar!, Set to false to remove bar entirely for more realistic gameplay!
		weaponAmmoBar = false

	#Properties relating to particles
	[client.particle]
		#The minimum duration in ticks before bullet holes will disappear
		#Range: > 0
		bulletHoleLifeMin = 250
		#The maximum duration in ticks before bullet holes will disappear
		#Range: > 0
		bulletHoleLifeMax = 800
		#The percentage of the maximum life that must pass before particles begin fading away. 0 makes the particles always fade and 1 removes facing completely
		#Range: 0.0 ~ 1.0
		bulletHoleFadeThreshold = 0.98
		#If true, blood will will spawn from entities that are hit from a projectile
		enableBlood = false

	#Properties relating to controls
	[client.controls]
		#A value to multiple the mouse sensitivity by when aiming down weapon sights. Go to (Options > Controls > Mouse Settings > ADS Sensitivity) in game to change this!
		#Range: 0.0 ~ 2.0
		aimDownSightSensitivity = 0.75
		#Click to toggle aim on and off in game, instead of holding your aim button, the only way to utilize the toggleAim Keybind at this point!
		toggleAim = false
		#The delay in ticks before being able to activate your toggleAim again, recommended to leave alone or increase past default!
		#Range: 1 ~ 60
		toggleAimDelay = 8
		#Press to use a burst fire a gun, or hold to continue a burst, un-clicking cancels your burst
		burstPress = true

	#Properties relating to improving graphical performance (Currently unsupported, do not attempt to change these settings until announcements are made about these features!)
	[client.quality]
		#If enabled all main weapons will be unloaded and replaced with lower quality and legacy models, not all guns maybe replaced with this mode!
		reducedGuiWeaponQuality = false

	#Configuration for HUD additions
	[client.weaponGui]
		#Show your ammunition as numbers, reloading timer, weapon icon, and fire mode all on the HUD.
		weaponGui = true

		#Configuration for HUD additions
		[client.weaponGui.weaponTypeIcon]
			#Display the weapon type Icon on your HUD.
			showWeaponIcon = true
			#Size of the weapon type Icon on your HUD
			#Range: 0.01 ~ 4.0
			weaponIconSize = 1.0
			#X Position on your HUD.
			#Range: -500.0 ~ 500.0
			XLocation = 0.0
			#Y Position on your HUD.
			#Range: -500.0 ~ 500.0
			YLocation = 0.0

		#Configuration for HUD additions
		[client.weaponGui.weaponFireMode]
			#Display the weapon's fire mode on your HUD.
			showWeaponFireMode = true
			#Size of the weapon's fire mode on your HUD
			#Range: 0.01 ~ 4.0
			weaponFireModeSize = 1.0
			#X Position on your HUD.
			#Range: -500.0 ~ 500.0
			XLocation = 0.0
			#Y Position on your HUD.
			#Range: -500.0 ~ 500.0
			YLocation = 0.0

		#Configuration for HUD additions
		[client.weaponGui.weaponAmmoCounter]
			#Display the amount of ammunition your weapon holds and can hold on your HUD.
			showWeaponAmmoCounter = true
			#Size of the weapon ammunition counter on your HUD
			#Range: 0.01 ~ 4.0
			weaponAmmoCounterSize = 1.0
			#X Position on your HUD.
			#Range: -500.0 ~ 500.0
			XLocation = 0.0
			#Y Position on your HUD.
			#Range: -500.0 ~ 500.0
			YLocation = 0.0

		#Configuration for HUD reloading timer bar
		[client.weaponGui.weaponReloadTimer]
			#Display the amount of ammunition your weapon holds and can hold on your HUD.
			showWeaponAmmoCounter = true
			#Size of the weapon ammunition counter on your HUD
			#Range: 0.01 ~ 4.0
			weaponAmmoCounterSize = 1.0
			#X Position on your HUD.
			#Range: -500.0 ~ 500.0
			XLocation = 0.0
			#Y Position on your HUD.
			#Range: -500.0 ~ 500.0
			YLocation = 0.0

