onEvent('recipes', (event) => {

    //Applied Energistics Creative Storage Cell
    event.recipes.extendedcrafting.shaped_table({
        pattern: [
            'ABCCDCCBA',
            'BEFCACFEB',
            'CFEGHGEFC',
            'CCGIJIGCC',
            'KAHJLJHAK',
            'CCGIJIGCC',
            'CFEGHGEFC',
            'BEFCACFEB',
            'ABCCDCCBA',
        ],
        key: {
            A: {item: 'draconicevolution:chaos_shard', },
            B: {item: 'appliedenergistics2:purified_fluix_crystal', },
            C: {item: 'projectred-core:silicon', },
            D: {item: 'mekanism:creative_bin', },
            E: {item: 'appliedenergistics2:calculation_processor', },
            F: {item: 'appliedenergistics2:engineering_processor', },
            G: {item: 'appliedenergistics2:logic_processor', },
            H: {item: 'appliedenergistics2:128_cubed_spatial_storage_cell', },
            I: {item: 'ae2extras:16m_storage_cell', },
            J: {item: 'mysticalagradditions:creative_essence', },
            K: {item: 'storagedrawers:creative_storage_upgrade', },
            L: {item: 'storagedrawers:creative_vending_upgrade',},
        },
        result: {item: 'appliedenergistics2:creative_storage_cell', },
    }).id(`kubejs:appliedenergistics2/creative_storage_cell`)

    //Refined Storage Creative Item Storage Disk
    event.recipes.extendedcrafting.shaped_table({
        pattern: [
            'NABBBBBAN',
            'ACDBMBDCA',
            'BDCEFECDB',
            'BBEGHGEBB',
            'BMIHJHKMB',
            'BBEGHGEBB',
            'BDCELECDB',
            'ACDBMBDCA',
            'NABBBBBAN',
        ],
        key: {
            A: {item: 'refinedstorage:processor_binding', },
            B: {item: 'projectred-core:silicon', },
            C: {item: 'refinedstorage:advanced_processor', },
            D: {item: 'refinedstorage:basic_processor', },
            E: {item: 'refinedstorage:improved_processor', },
            F: {item: 'extrastorage:disk_1024k', },
            G: {item: 'refinedstorage:64k_storage_disk', },
            H: {item: 'mysticalagradditions:creative_essence', },
            I: {item: 'extrastorage:disk_1024k', },
            J: {item: 'storagedrawers:creative_storage_upgrade', },
            K: {item: 'extrastorage:disk_1024k', },
            L: {item: 'extrastorage:disk_1024k', },
            M: {item: 'extradisks:infinite_storage_disk', },
            N: {item: 'extradisks:withering_processor', },
        },
        result: {item: 'refinedstorage:creative_storage_disk', },
    }).id(`kubejs:refinedstorage/creative_storage_disk`)

    //Refined Storage Creative Fluid storage Disk
    event.recipes.extendedcrafting.shaped_table({
        pattern: [
            'OABBBBBAO',
            'ACDBNBDCA',
            'BDCEFECDB',
            'BBEGHIEBB',
            'BNJHKHLNB',
            'BBEMHGEBB',
            'BDCELECDB',
            'ACDBNBDCA',
            'OABBBBBAO',
        ],
        key: {
            A: {item: 'refinedstorage:processor_binding', },
            B: {item: 'projectred-core:silicon', },
            C: {item: 'refinedstorage:advanced_processor', },
            D: {item: 'refinedstorage:basic_processor', },
            E: {item: 'refinedstorage:improved_processor', },
            F: {item: 'extrastorage:disk_65536k_fluid', },
            G: {item: 'refinedstorage:4096k_fluid_storage_disk', },
            H: {item: 'mysticalagradditions:creative_essence', },
            I: {item: 'refinedstorage:4096k_fluid_storage_disk', },
            J: {item: 'extrastorage:disk_65536k_fluid', },
            K: {item: 'storagedrawers:creative_storage_upgrade', },
            L: {item: 'extrastorage:disk_65536k_fluid', },
            M: {item: 'refinedstorage:4096k_fluid_storage_disk', },
            N: {item: 'extradisks:infinite_fluid_storage_disk', },
            O: {item: 'extradisks:withering_processor', },
        },
        result: {item: 'refinedstorage:creative_fluid_storage_disk', },
    }).id(`kubejs:refinedstorage/creative_fluid_storage_disk`)

    //Botania Creative Mana Tablet
    event.recipes.extendedcrafting.shaped_table({
        pattern: [
            'ABABABABA',
            'BACACACAB',
            'ACDEDEDCA',
            'BAEFGFEAB',
            'ACDGHGDCA',
            'BAEFGFEAB',
            'ACDEDEDCA',
            'BACACACAB',
            'ABABABABA',
        ],
        key: {
            A: {item: 'botania:terrasteel_ingot', },
            B: {item: 'botania:mana_pearl', },
            C: {item: 'botania:mana_diamond', },
            D: {item: 'botania:gaia_ingot', },
            E: {item: 'botania:manasteel_ingot', },
            F: {type: 'forge:nbt',
                item: 'botania:mana_tablet',
                count: 1,
                nbt: '{mana:500000}', },
            G: {item: 'mysticalagradditions:creative_essence', },
            H: {item: 'botania:mana_tablet', },
        },
        result: {type: 'forge:nbt',
            item: 'botania:mana_tablet',
            count: 1,
            nbt: '{mana:500000, creative: 1b}', },
    }).id(`kubejs:botania/mana_tablet`)

    //Mekanism Creative Fluid Tank
    event.recipes.extendedcrafting.shaped_table({
        pattern: [
            'ABCBCBCBA',
            'BCDCECDCB',
            'CDFBGBFDC',
            'BCBHKHBCB',
            'CEGILIGEC',
            'BCBHKHBCB',
            'CJFBGBFJC',
            'BCJCECJCB',
            'ABCBCBCBA',
        ],
        key: {
            A: {item: 'mekanism:dynamic_tank', },
            B: {item: 'mekanism:alloy_atomic', },
            C: {item: 'minecraft:iron_ingot', },
            D: {item: 'fluidtank:tank_diamond', },
            E: {item: 'fluidtank:tank_star', },
            F: {item: 'industrialforegoing:supreme_black_hole_tank', },
            G: {item: 'enderstorage:ender_tank', },
            H: {item: 'extendedcrafting:ultimate_singularity', },
            I: {item: 'mekanism:ultimate_fluid_tank', },
            J: {item: 'tconstruct:seared_ingot_gauge', },
            K: {item: 'mysticalagradditions:creative_essence', },
            L: {type: "forge:nbt",
                item: "mekanism:creative_energy_cube",
                count: 1,
                nbt: '{mekData:{EnergyContainers:[{Container:0b,stored:"18446744073709551615.9999"}]}}', },
        },
        result: {item: 'mekanism:creative_fluid_tank', },
    }).id(`kubejs:mekanism/creative_fluid_tank`)

    //Draconic Evolution Creative Capacitor
    event.recipes.extendedcrafting.shaped_table({
        pattern: [
            'ABBBBBBBA',
            'BABBHBBAB',
            'BBCDDDCBB',
            'BBDEFEDBB',
            'BHDFGFDHB',
            'BBDEFEDBB',
            'BBCDDDCBB',
            'BABBHBBAB',
            'ABBBBBBBA',
        ],
        key: {
            A: {item: 'draconicevolution:awakened_draconium_block', },
            B: {item: 'draconicevolution:infused_obsidian', },
            C: {item: 'draconicevolution:chaotic_capacitor', },
            D: {item: 'draconicevolution:chaotic_core', },
            E: {item: 'extendedcrafting:ultimate_singularity', },
            F: {item: 'draconicevolution:chaos_shard', },
            G: {item: 'draconicevolution:reactor_core', },
            H: {item: 'mysticalagradditions:creative_essence', },
        },
        result: {item: 'draconicevolution:creative_capacitor', },
    }).id(`kubejs:draconicevolution/creative_capacitor`)

    //Mystical Agriculture Creative Essence
    event.recipes.extendedcrafting.shaped_table({
        pattern: [
            "ABCDEDFGH",
            "IJDKDLDMN",
            "ODPDQDRDS",
            "DTDUVUDWD",
            "XDYZ123D4",
            "D5DU6UD7D",
            "aDsDdDfDg",
            "hjDkDlDqw",
            "ertDyDuio",
        ],
        key: {
            A: {item: "mysticalagriculture:nickel_seeds", },
            B: {item: "mysticalagriculture:manasteel_seeds", },
            C: {item: "mysticalagriculture:experience_seeds", },
            D: {item: "mysticalagradditions:insanium_essence", },
            E: {item: "mysticalagriculture:diamond_seeds", },
            F: {item: "mysticalagriculture:constantan_seeds", },
            G: {item: "mysticalagriculture:ghast_seeds", },
            H: {item: "mysticalagriculture:lumium_seeds", },
            I: {item: "mysticalagriculture:redstone_seeds", },
            J: {item: "mysticalagriculture:elementium_seeds", },
            K: {item: "mysticalagriculture:queens_slime_seeds", },
            L: {item: "mysticalagriculture:hepatizon_seeds", },
            M: {item: "mysticalagriculture:fluix_seeds", },
            N: {item: "mysticalagriculture:pig_iron_seeds", },
            O: {item: "mysticalagriculture:hop_graphite_seeds", },
            P: {item: "mysticalagriculture:draconium_seeds", },
            Q: {item: "mysticalagriculture:awakened_draconium_seeds", },
            R: {item: "mysticalagriculture:fiery_ingot_seeds", },
            S: {item: "mysticalagriculture:invar_seeds", },
            T: {item: "mysticalagriculture:electrum_seeds", },
            U: {item: "extendedcrafting:ultimate_singularity", },
            V: {item: "mysticalagriculture:squid_seeds", },
            W: {item: "mysticalagriculture:starmetal_seeds", },
            X: {item: "mysticalagriculture:wither_skeleton_seeds", },
            Y: {item: "mysticalagriculture:refined_obsidian_seeds", },
            Z: {item: "mysticalagriculture:earth_seeds", },
            1: {item: "mysticalagriculture:master_infusion_crystal", },
            2: {item: "mysticalagriculture:fire_seeds", },
            3: {item: "mysticalagriculture:terrasteel_seeds", },
            4: {item: "mysticalagriculture:netherite_seeds", },
            5: {item: "mysticalagriculture:manyullyn_seeds", },
            6: {item: "mysticalagriculture:water_seeds", },
            7: {item: "mysticalagriculture:uranium_seeds", },
            a: {item: "mysticalagriculture:signalum_seeds", },
            s: {item: "mysticalagriculture:nether_star_seeds", },
            d: {item: "mysticalagriculture:pink_slime_seeds", },
            f: {item: "mysticalagriculture:dragon_egg_seeds", },
            g: {item: "mysticalagriculture:cobalt_seeds", },
            h: {item: "mysticalagriculture:enderman_seeds", },
            j: {item: "mysticalagriculture:refined_glowstone_seeds", },
            k: {item: "mysticalagriculture:enderium_seeds", },
            l: {item: "mysticalagriculture:fluorite_seeds", },
            q: {item: "mysticalagriculture:steel_seeds", },
            w: {item: "mysticalagriculture:tinkers_bronze_seeds", },
            e: {item: "mysticalagriculture:osmium_seeds", },
            r: {item: "mysticalagriculture:lapis_lazuli_seeds", },
            t: {item: "mysticalagriculture:blaze_seeds", },
            y: {item: "mysticalagriculture:emerald_seeds", },
            u: {item: "mysticalagriculture:gold_seeds", },
            i: {item: "mysticalagriculture:rose_gold_seeds", },
            o: {item: "mysticalagriculture:end_seeds", },
        },
        result: {item: "mysticalagradditions:creative_essence", },
    }).id(`kubejs:mysticalagradditions/creative_essence`)

    //Blood Magic Creative Activation Crystal
    event.recipes.extendedcrafting.shaped_table({
        pattern: [
            "ABBBCDDDA",
            "EFGHIHGFJ",
            "EGKLKLKGJ",
            "EMNOPONMJ",
            "CIKPQPKIC",
            "RMNOPONMS",
            "RTKLKLKTS",
            "RFTHIHTFS",
            "AUUUCVVVA",
        ],
        key: {
            A: {item: "bloodmagic:bloodlightsigil", },
            B: {item: "bloodmagic:chargingrune", },
            C: {item: "bloodmagic:sigilofholding", },
            D: {item: "bloodmagic:selfsacrificerune", },
            E: {item: "bloodmagic:accelerationrune", },
            F: {item: "bloodmagic:airsigil", },
            G: {item: "bloodmagic:demonslate", },
            H: {item: "bloodmagic:voidsigil", },
            I: {item: "bloodmagic:watersigil", },
            J: {item: "bloodmagic:altarcapacityrune", },
            K: {item: "bloodmagic:life_essence_bucket", },
            L: {item: "bloodmagic:reinforcedslate", },
            M: {item: "bloodmagic:lavasigil", },
            N: {item: "bloodmagic:blankslate", },
            O: {item: "mysticalagradditions:creative_essence", },
            P: {item: "bloodmagic:activationcrystalweak", },
            Q: {item: "bloodmagic:altar", },
            R: {item: "bloodmagic:sacrificerune", },
            S: {item: "bloodmagic:bettercapacityrune", },
            T: {item: "bloodmagic:infusedslate", },
            U: {item: "bloodmagic:speedrune", },
            V: {item: "bloodmagic:dislocationrune", },
        },
        result: {item: "bloodmagic:activationcrystalcreative", },
    }).id(`kubejs:bloodmagic/activationcrystalcreative`)

    //Mekanism Creative Gas Tank
    event.recipes.extendedcrafting.shaped_table({
        pattern: [
            "ABABABABA",
            "BABABABAB",
            "ABDBABEBA",
            "BABCDCBAB",
            "ABAEFGABA",
            "BABCHCBAB",
            "ABHBABGBA",
            "BABABABAB",
            "ABABABABA",
        ],
        key: {
            A: {item: "mekanism:alloy_atomic", },
            B: {item: "mekanism:ingot_osmium", },
            C: {item: "mysticalagradditions:creative_essence", },
            D: {type: "forge:nbt",
                item: "mekanism:ultimate_chemical_tank",
                count: 1,
                nbt: '{mekData:{GasTanks:[{Tank:0b,stored:{gasName:"mekanism:ethene",amount:512000L}}]}}', },
            E: {type: "forge:nbt",
                item: "mekanism:ultimate_chemical_tank",
                count: 1,
                nbt: '{mekData:{GasTanks:[{Tank:0b,stored:{gasName:"mekanismgenerators:fusion_fuel",amount:512000L}}]}}', },
            F: {item: "mekanism:creative_fluid_tank", },
            G: {type: "forge:nbt",
                item: "mekanism:ultimate_chemical_tank",
                count: 1,
                nbt: '{mekData:{GasTanks:[{Tank:0b,stored:{gasName:"mekanism:nutritional_paste",amount:512000L}}]}}', },
            H: {type: "forge:nbt",
                item: "mekanism:ultimate_chemical_tank",
                count: 1,
                nbt: '{mekData:{GasTanks:[{Tank:0b,stored:{gasName:"mekanism:uranium_hexafluoride",amount:512000L}}]}}', },
        },
        result: {item: "mekanism:creative_chemical_tank", },
    }).id(`kubejs:mekanism/creative_chemical_tank`)

    //Creative Storage Drawer Vending Upgrade
    event.recipes.extendedcrafting.shaped_table({
        pattern: [
            "ABBBCBBBA",
            "BDBBEBBDB",
            "BBFGHGFBB",
            "BBGIJIGBB",
            "CEHJKJHEC",
            "BBGIJIGBB",
            "BBFGHGFBB",
            "BDBBEBBDB",
            "ABBBCBBBA",
        ],
        key: {
            A: {item: "draconicevolution:chaos_shard", },
            B: {item: "draconicevolution:draconium_block", },
            C: {item: "mekanismgenerators:tritium_bucket", },
            D: {item: "mekanism:supercharged_coil", },
            E: {item: "draconicevolution:chaotic_crafting_injector", },
            F: {item: "mysticalagriculture:infusion_pedestal", },
            G: {item: "draconicevolution:draconium_core", },
            H: {type: "forge:nbt",
                item: "mekanism:ultimate_energy_cube",
                count: 1,
                nbt: '{mekData:{EnergyContainers:[{Container:0b,stored:"256000000"}]}}', },
            I: {item: "extendedcrafting:ultimate_singularity", },
            J: {item: "storagedrawers:upgrade_template", },
            K: {item: "storagedrawers:creative_storage_upgrade", },
        },
        result: {item: "storagedrawers:creative_vending_upgrade", },
    }).id(`kubejs:storagedrawers/creative_vending_upgrade`)

    //Simply Jetpacks Creative Jetpack
    event.recipes.extendedcrafting.shaped_table({
        pattern: [
            'ABCCDCCBA',
            'BEFCACFEB',
            'CFEGHGEFC',
            'CCGIJIGCC',
            'KAHJLJHAK',
            'CCGIJIGCC',
            'CFEGHGEFC',
            'BEFCACFEB',
            'ABCCDCCBA',
        ],
        key: {
            A: {item: 'create_stuff_additions:encased_jet_chestplate', },
            B: {item: 'xreliquary:angelic_feather', },
            C: {item: 'minecraft:elytra', },
            D: {item: 'forbidden_arcanus:golden_dragon_scale', },
            E: {item: 'simplyjetpacks:jetpack_mek4_armored', },
            F: {item: 'simplyjetpacks:jetpack_te4_armored', },
            G: {item: 'simplyjetpacks:jetpack_ie3_armored', },
            H: {item: 'simplyjetpacks:jetpack_vanilla4_armored', },
            I: {item: 'overloaded:true_infinite_capacitor', },
            J: {item: 'mysticalagradditions:creative_essence', },
            K: {item: 'mekanism:jetpack_armored', },
            L: {item: 'simplyjetpacks:jetpack_te5_enderium',},
        },
        result: {item: 'simplyjetpacks:jetpack_creative', },
    }).id(`kubejs:simplyjetpacks/jetpack_creative`)

    //Ars Nouveau Creative Source Jar
    event.recipes.extendedcrafting.shaped_table({
        pattern: [
            'ABCCDCCBA',
            'BMFCACFMB',
            'CFEGHGEFC',
            'CCGIJIGCC',
            'KAHJLJHAK',
            'CCGIJIGCC',
            'CFEGHGEFC',
            'BMFCACFMB',
            'ABCCDCCBA',
        ],
        key: {
            A: {item: 'ars_nouveau:summon_focus', },
            B: {item: 'ars_nouveau:mana_gem_block', },
            C: {item: 'ars_nouveau:mythical_clay', },
            D: {item: 'ars_nouveau:jar_of_light', },
            E: {item: 'botania:gaia_spreader', },
            F: {item: 'botania:lens_flare', },
            G: {item: 'astralsorcery:resonating_gem', },
            H: {item: 'astralsorcery:prism', },
            I: {item: 'mythicbotany:mana_infuser', },
            J: {item: 'mysticalagradditions:creative_essence', },
            K: {item: 'botanicalmachinery:mana_battery', },
            L: {item: 'ars_nouveau:mana_jar',},
            M: {item: 'botania:elven_spreader',},
        },
        result: {item: 'ars_nouveau:creative_mana_jar', },
    }).id(`kubejs:ars_nouveau/creative_mana_jar`)

    //Ars Nouveau Creative Spell Book
    event.recipes.extendedcrafting.shaped_table({
        pattern: [
            'ABCCDCCBA',
            'BMFCACFMB',
            'CFEGHGEFC',
            'CCGIJIGCC',
            'KAHJLJHAK',
            'CCGIJIGCC',
            'CFEGHGEFC',
            'BMFCACFMB',
            'ABCCDCCBA',
        ],
        key: {
            A: {item: 'ars_nouveau:spell_prism', },
            B: {item: 'tomeofblood:blood_tome_two', },
            C: {item: 'terraqueous:ender_book', },
            D: {item: 'extendedcrafting:ultimate_singularity', },
            E: {item: 'mythicbotany:fire_ring', },
            F: {item: 'draconicevolution:awakened_core', },
            G: {item: 'bloodmagic:masterbloodorb', },
            H: {item: 'enigmaticlegacy:lore_inscriber', },
            I: {item: 'draconicevolution:chaotic_crafting_injector', },
            J: {item: 'mysticalagradditions:creative_essence', },
            K: {item: 'draconicevolution:energy_transfuser', },
            L: {item: 'ars_nouveau:archmage_spell_book',},
            M: {item: 'mythicbotany:andwari_ring',},
        },
        result: {item: 'ars_nouveau:creative_spell_book', },
    }).id(`kubejs:ars_nouveau/creative_spell_book`)

    //Rats Creative Cheese
    event.recipes.extendedcrafting.shaped_table({
        pattern: [
            'ABCCDCCBA',
            'BMFCACFMB',
            'CFEGHGEFC',
            'CCGIJIGCC',
            'KAHJLJHAK',
            'CCGIJIGCC',
            'CFEGHGEFC',
            'BMFCACFMB',
            'ABCCDCCBA',
        ],
        key: {
            A: {item: 'rats:idol_of_ratlantis', },
            B: {item: 'rats:block_of_cheese', },
            C: {item: 'rats:chunky_cheese_token', },
            D: {item: 'rats:ratlantis_rat_skull', },
            E: {item: 'rats:cheese', },
            F: {item: 'rats:ratlantean_flame', },
            G: {item: 'rats:marbled_cheese_rat_head', },
            H: {item: 'rats:arcane_technology', },
            I: {item: 'rats:psionic_rat_brain', },
            J: {item: 'mysticalagradditions:creative_essence', },
            K: {item: 'extendedcrafting:ultimate_singularity', },
            L: {item: 'rats:rat_upgrade_extreme_energy',},
            M: {item: 'rats:ratbow_essence',},
        },
        result: {item: 'rats:creative_cheese', },
    }).id(`kubejs:rats/creative_cheese`)

    //Create Creative Motor
    event.recipes.extendedcrafting.shaped_table({
        pattern: [
            'ABCCDCCBA',
            'BMFCACFMB',
            'CFEGHGEFC',
            'CCGIJIGCC',
            'KAHJLJHAK',
            'CCGIJIGCC',
            'CFEGHGEFC',
            'BMFCACFMB',
            'ABCCDCCBA',
        ],
        key: {
            A: {item: 'extendedcrafting:crystaltine_catalyst', },
            B: {item: 'create:brass_block', },
            C: {item: 'create:large_cogwheel', },
            D: {item: 'create_stuff_additions:tuned_brass_moped_item', },
            E: {item: 'create:rotation_speed_controller', },
            F: {item: 'rftoolscontrol:cpu_core_2000', },
            G: {item: 'rftoolscontrol:ram_chip', },
            H: {item: 'draconicevolution:reactor_prt_rotor_full', },
            I: {item: 'projectred-core:motor', },
            J: {item: 'mysticalagradditions:creative_essence', },
            K: {item: 'extendedcrafting:ultimate_singularity', },
            L: {item: 'projectred-integration:buffer_cell_gate',},
            M: {item: 'create:crushing_wheel',},
        },
        result: {item: 'create:creative_motor', },
    }).id(`kubejs:rats/creative_cheese`)

    //Create Creative Fluid Tank
    event.recipes.extendedcrafting.shaped_table({
        pattern: [
            'ABCCDCCBA',
            'BMFCACFMB',
            'CFEGHGEFC',
            'CCGIJIGCC',
            'KAHJLJHAK',
            'CCGIJIGCC',
            'CFEGHGEFC',
            'BMFCACFMB',
            'ABCCDCCBA',
        ],
        key: {
            A: {item: 'fluidtank:tank_star', },
            B: {item: 'cyclic:wireless_fluid', },
            C: {item: 'fluidtank:reservoir_stone', },
            D: {item: 'overloaded:infinite_water_source', },
            E: {item: 'draconicevolution:fluid_gate', },
            F: {item: 'bloodmagic:watersigil', },
            G: {item: 'enderstorage:ender_tank', },
            H: {item: 'rftoolsutility:waterbreathing_module', },
            I: {item: 'industrialforegoing:fluid_collector', },
            J: {item: 'mysticalagradditions:creative_essence', },
            K: {item: 'extendedcrafting:ultimate_singularity', },
            L: {item: 'mysticaladaptations:insanium_watering_can',},
            M: {item: 'thermal:fluid_cell',},
        },
        result: {item: 'create:creative_fluid_tank', },
    }).id(`kubejs:rats/creative_fluid_tank`)

    //Create Creative Crate
    event.recipes.extendedcrafting.shaped_table({
        pattern: [
            'ABCCDCCBA',
            'BMFCACFMB',
            'CFEGHGEFC',
            'CCGIJIGCC',
            'KAHJLJHAK',
            'CCGIJIGCC',
            'CFEGHGEFC',
            'BMFCACFMB',
            'ABCCDCCBA',
        ],
        key: {
            A: {item: 'mekanism:ultimate_bin', },
            B: {item: 'immersiveengineering:reinforced_crate', },
            C: {item: 'druidcraft:crate', },
            D: {item: 'ae2extras:16m_cell_component', },
            E: {item: 'draconicevolution:draconium_chest', },
            F: {item: 'appliedenergistics2:64k_cell_component', },
            G: {item: 'enderstorage:ender_chest', },
            H: {item: 'industrialforegoing:black_hole_controller', },
            I: {item: 'industrialforegoing:supreme_black_hole_unit', },
            J: {item: 'mysticalagradditions:creative_essence', },
            K: {item: 'extendedcrafting:ultimate_singularity', },
            L: {item: 'extradisks:infinite_storage_block',},
            M: {item: 'mekanism:personal_chest',},
        },
        result: {item: 'create:creative_crate', },
    }).id(`kubejs:rats/creative_crate`)

})
